# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked_books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded_books',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_books', to='index.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ManyToManyField(related_name='uploaded_books', to='index.User'),
        ),
    ]
